### ISSUE TITLE
Quizdown-js for interactive videos

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [bonartm/quizdown-js#10]
Hello, 

I would like to fork and extend quizdown-js to support interactive videos for teaching purpose, something like:

```html
<div class="quizdown" video="https://www.youtube.com/watch?v=YOUTUBE_VIDEO">
	---
	primary_color: steelblue
	shuffle_questions: false
	shuffle_answers: true
	---

	### Select your superpowers!

	! 30

	- [ ] Enhanced Strength
	- [ ] Levitation
	- [x] Shapeshifting

	### What's the capital of Germany?

	! 120

	> Hint: The _largest_ city in Germany...

	1. [x] Berlin
	1. [ ] Frankfurt
	1. [ ] Paris
	1. [ ] Cologne
</div>
```

In this imaginative example, the question should stop (or hide) the video and appears at 30 seconds of video, and the second question will be show 120 seconds, so, if the student answers correctly the video continue.

I would like to implement something like that using quizdown-js, I believe that it is not difficult to achieve this result because we just need to add the time information and indicates the video. What do you think? How can I contribute?

Best regards
Rodrigo

**Comment by bonartm** [comment]
Sounds interesting and the [youtube player api](https://developers.google.com/youtube/iframe_api_reference) is quite customizable. Regarding the syntax I would prefer a solution that uses the already implemented yaml based options. This makes it unnecessary to modify the parser and is inline with the existing syntax.

```markdown
---
primary_color: "steelblue"
shuffle_questions: false
shuffle_answers: true
video: "https://www.youtube.com/watch?v=YOUTUBE_VIDEO"
---

### Select your superpowers!

---
seconds: 30
---

- [ ] Enhanced Strength
- [ ] Levitation
- [x] Shapeshifting

### What's the capital of Germany?

---
seconds: 120
---

> Hint: The _largest_ city in Germany...

1. [x] Berlin
1. [ ] Frankfurt
1. [ ] Paris
1. [ ] Cologne
```

**Comment by rodrigoprestesmachado** [comment]
I believe that the solution with yaml syntax is nice. How can I contribute? let split the task and develop it =)

**Comment by bonartm** [comment]
Hi,

I have setup a first demo in the branch `10_video` (0c75639c19517e0f2fe916b8f5c735891176f5b2). Feel free to use this for development of the feature. 

Three new options can be specified in the quizdown: `video_id` , `start_seconds`, `end_seconds`. 
The video is loaded for each question and plays the video from `start_seconds` to `end_seconds`. User controls are disabled as best as possible so that the user can only watch the specified section from the video (of course she/he can always watch the full video on youtube). 

The generic youtube player is implemented in the component `YoutubePlayer.svelte`. It takes care of setting up the library and initializing a player object. The player object can then be controlled from within higher level components. 

A basic `VideoView.svelte` is used to display the video inside the quiz with a custom start/pause button. Which user interactions do you have in mind? The current state might be a good starting point for improvements in the main components `QuizSection` and `VideoView`.

**Comment by rodrigoprestesmachado** [comment]
Very nice!!! You did a very nice jog! I was imagining a scenario a little bit different, but I will test it to see if the user's interactions is enough.

**Comment by bonartm** [comment]
> The objective is to try to make a student think/reflect about the video content, so this "fast feedback" maybe be important in this interactive video scenario

You are right. This should be implemented in a generic way and should be treated independently from the video content. I have opened #12 for a discussion on that.

**Comment by bonartm** [comment]
I want to focus on making the core library more stable so this feature is out of scope for now. I will add a comment to the readme though for reference.
